[package]
name = "bismarck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.7"
serde = "1.0.195"
serde_json = "1.0.111"
tracing = "0.1.23"
tracing-subscriber = "^0.3"
dotenv = "^0.15.0"
chrono = "0.4.31"
git2 = "0.18.1"
tokio = { version = "1.0", features = ["macros", "signal", "rt-multi-thread"] }
rustrict = "0.7.19"
sqlx = { version = "0.7", features = [ "runtime-async-std", "tls-rustls", "sqlite", "macros" ] }
reqwest = { version = "0.11", features = ["json"] }